
const Products = require("./modules/ProductsModule")
const fillProduct = async () => {
    //ריצוף
    await Products.create({ name: "ריצוף ", price: 700, description: "ריצוץ מדהים לכל בית", category: "ריצוף", imageUrl: `http://localhost:5000/floor/r1.png` })
    await Products.create({ name: "ריצוף", price: 830, description: "ריצוץ מדהים לכל בית", category: "ריצוף", imageUrl: `http://localhost:5000/floor/r2.png` })
    await Products.create({ name: "ריצוף", price: 720, description: "ריצוץ מדהים לכל בית", category: "ריצוף", imageUrl: `http://localhost:5000/floor/r3.png` })
    await Products.create({ name: "ריצוף", price: 620, description: "ריצוץ מדהים לכל בית", category: "ריצוף", imageUrl: `http://localhost:5000/floor/r4.png` })
    await Products.create({ name: "ריצוף", price: 700, description: "ריצוץ מדהים לכל בית", category: "ריצוף", imageUrl: `http://localhost:5000/floor/r5.png` })
    await Products.create({ name: "ריצוף", price: 550, description: "ריצוץ מדהים לכל בית", category: "ריצוף", imageUrl: `http://localhost:5000/floor/r6.png` })
    await Products.create({ name: "ריצוף", price: 170, description: "ריצוץ מדהים לכל בית", category: "ריצוף", imageUrl: `http://localhost:5000/floor/r7.png` })
    await Products.create({ name: "ריצוף", price: 745, description: "ריצוץ מדהים לכל בית", category: "ריצוף", imageUrl: `http://localhost:5000/floor/r8.png` })
    await Products.create({ name: "ריצוף", price: 652, description: "ריצוץ מדהים לכל בית", category: "ריצוף", imageUrl: `http://localhost:5000/floor/r9.png` })
    await Products.create({ name: "ריצוף", price: 778, description: "ריצוץ מדהים לכל בית", category: "ריצוף", imageUrl: `http://localhost:5000/floor/r10.png` })
    await Products.create({ name: "ריצוף", price: 790, description: "ריצוץ מדהים לכל בית", category: "ריצוף", imageUrl: `http://localhost:5000/floor/r11.png` })
    await Products.create({ name: "ריצוף", price: 750, description: "ריצוץ מדהים לכל בית", category: "ריצוף", imageUrl: `http://localhost:5000/floor/r12.png` })
    await Products.create({ name: "ריצוף", price: 680, description: "ריצוץ מדהים לכל בית", category: "ריצוף", imageUrl: `http://localhost:5000/floor/r13.png` })
    await Products.create({ name: "ריצוף", price: 500, description: "ריצוץ מדהים לכל בית", category: "ריצוף", imageUrl: `http://localhost:5000/floor/r14.png` })
    await Products.create({ name: "ריצוף", price: 450, description: "ריצוץ מדהים לכל בית", category: "ריצוף", imageUrl: `http://localhost:5000/floor/r15.png` })
    await Products.create({ name: "ריצוף", price: 550, description: "ריצוץ מדהים לכל בית", category: "ריצוף", imageUrl: `http://localhost:5000/floor/r16.png` })
    await Products.create({ name: "ריצוף", price: 720, description: "ריצוץ מדהים לכל בית", category: "ריצוף", imageUrl: `http://localhost:5000/floor/r17.png` })
    await Products.create({ name: "ריצוף", price: 730, description: "ריצוץ מדהים לכל בית", category: "ריצוף", imageUrl: `http://localhost:5000/floor/r18.png` })
    // "חדרי אמבטיה"
    await Products.create({ name: "חדרי אמבטיה", price: 7000, description: "חדרי אמבטיה מפוארים", category: "חדרי אמבטיה", imageUrl: `http://localhost:5000/BathRooms/b1.png` })
    await Products.create({ name: "חדרי אמבטיה", price: 7800, description: "חדרי אמבטיה מפוארים", category: "חדרי אמבטיה", imageUrl: `http://localhost:5000/BathRooms/b2.png` })
    await Products.create({ name: "חדרי אמבטיה", price: 9000, description: "חדרי אמבטיה מפוארים", category: "חדרי אמבטיה", imageUrl: `http://localhost:5000/BathRooms/b3.png` })
    await Products.create({ name: "חדרי אמבטיה", price: 7500, description: "חדרי אמבטיה מפוארים", category: "חדרי אמבטיה", imageUrl: `http://localhost:5000/BathRooms/b4.png` })
    await Products.create({ name: "חדרי אמבטיה", price: 7200, description: "חדרי אמבטיה מפוארים", category: "חדרי אמבטיה", imageUrl: `http://localhost:5000/BathRooms/b5.png` })
    await Products.create({ name: "חדרי אמבטיה", price: 8800, description: "חדרי אמבטיה מפוארים", category: "חדרי אמבטיה", imageUrl: `http://localhost:5000/BathRooms/b6.png` })
    await Products.create({ name: "חדרי אמבטיה", price: 6500, description: "חדרי אמבטיה מפוארים", category: "חדרי אמבטיה", imageUrl: `http://localhost:5000/BathRooms/b7.png` })
    await Products.create({ name: "חדרי אמבטיה", price: 4300, description: "חדרי אמבטיה מפוארים", category: "חדרי אמבטיה", imageUrl: `http://localhost:5000/BathRooms/b8.png` })
    await Products.create({ name: "חדרי אמבטיה", price: 4500, description: "חדרי אמבטיה מפוארים", category: "חדרי אמבטיה", imageUrl: `http://localhost:5000/BathRooms/b9.png` })
    //"ארונות"
    await Products.create({ name: "ארונות", price: 1200, description: "ארונות מעוצבים יפייפה", category: "ארונות", imageUrl: `http://localhost:5000/Cabinets/c1.png` })
    await Products.create({ name: "ארונות", price: 1500, description: "ארונות מעוצבים יפייפה", category: "ארונות", imageUrl: `http://localhost:5000/Cabinets/c2.png` })
    await Products.create({ name: "ארונות", price: 2500, description: "ארונות מעוצבים יפייפה", category: "ארונות", imageUrl: `http://localhost:5000/Cabinets/c3.png` })
    await Products.create({ name: "ארונות", price: 4500, description: "ארונות מעוצבים יפייפה", category: "ארונות", imageUrl: `http://localhost:5000/Cabinets/c4.png` })
    await Products.create({ name: "ארונות", price: 1000, description: "ארונות מעוצבים יפייפה", category: "ארונות", imageUrl: `http://localhost:5000/Cabinets/c5.png` })
    await Products.create({ name: "ארונות", price: 700, description: "ארונות מעוצבים יפייפה", category: "ארונות", imageUrl: `http://localhost:5000/Cabinets/c6.png` })
    await Products.create({ name: "ארונות", price: 750, description: "ארונות מעוצבים יפייפה", category: "ארונות", imageUrl: `http://localhost:5000/Cabinets/c7.png` })
    await Products.create({ name: "ארונות", price: 1300, description: "ארונות מעוצבים יפייפה", category: "ארונות", imageUrl: `http://localhost:5000/Cabinets/c8.png` })
    await Products.create({ name: "ארונות", price: 7500, description: "ארונות מעוצבים יפייפה", category: "ארונות", imageUrl: `http://localhost:5000/Cabinets/c9.png` })
    await Products.create({ name: "ארונות", price: 7120, description: "ארונות מעוצבים יפייפה", category: "ארונות", imageUrl: `http://localhost:5000/Cabinets/c10.png` })
    await Products.create({ name: "ארונות", price: 7000, description: "ארונות מעוצבים יפייפה", category: "ארונות", imageUrl: `http://localhost:5000/Cabinets/c11.png` })
    await Products.create({ name: "ארונות", price: 450, description: "ארונות מעוצבים יפייפה", category: "ארונות", imageUrl: `http://localhost:5000/Cabinets/c12.png` })
    await Products.create({ name: "ארונות", price: 700, description: "ארונות מעוצבים יפייפה", category: "ארונות", imageUrl: `http://localhost:5000/Cabinets/c13.png` })
    await Products.create({ name: "ארונות", price: 900, description: "ארונות מעוצבים יפייפה", category: "ארונות", imageUrl: `http://localhost:5000/Cabinets/c14.png` })
    await Products.create({ name: "ארונות", price: 1000, description: "ארונות מעוצבים יפייפה", category: "ארונות", imageUrl: `http://localhost:5000/Cabinets/c15.png` })
    await Products.create({ name: "ארונות", price: 1500, description: "ארונות מעוצבים יפייפה", category: "ארונות", imageUrl: `http://localhost:5000/Cabinets/c16.png` })
    await Products.create({ name: "ארונות", price: 1200, description: "ארונות מעוצבים יפייפה", category: "ארונות", imageUrl: `http://localhost:5000/Cabinets/c17.png` })
    await Products.create({ name: "ארונות", price: 1600, description: "ארונות מעוצבים יפייפה", category: "ארונות", imageUrl: `http://localhost:5000/Cabinets/c18.png` })
    await Products.create({ name: "ארונות", price: 1800, description: "ארונות מעוצבים יפייפה", category: "ארונות", imageUrl: `http://localhost:5000/Cabinets/c19.png` })
    await Products.create({ name: "ארונות", price: 1240, description: "ארונות מעוצבים יפייפה", category: "ארונות", imageUrl: `http://localhost:5000/Cabinets/c20.png` })
    await Products.create({ name: "ארונות", price: 1320, description: "ארונות מעוצבים יפייפה", category: "ארונות", imageUrl: `http://localhost:5000/Cabinets/c21.png` })
    await Products.create({ name: "ארונות", price: 8700, description: "ארונות מעוצבים יפייפה", category: "ארונות", imageUrl: `http://localhost:5000/Cabinets/c22.png` })
    await Products.create({ name: "ארונות", price: 700, description: "ארונות מעוצבים יפייפה", category: "ארונות", imageUrl: `http://localhost:5000/Cabinets/c23.png` })
    await Products.create({ name: "ארונות", price: 800, description: "ארונות מעוצבים יפייפה", category: "ארונות", imageUrl: `http://localhost:5000/Cabinets/c24.png` })
    await Products.create({ name: "ארונות", price: 9000, description: "ארונות מעוצבים יפייפה", category: "ארונות", imageUrl: `http://localhost:5000/Cabinets/c25.png` })
    await Products.create({ name: "ארונות", price: 750, description: "ארונות מעוצבים יפייפה", category: "ארונות", imageUrl: `http://localhost:5000/Cabinets/c26.png` })
    await Products.create({ name: "ארונות", price: 740, description: "ארונות מעוצבים יפייפה", category: "ארונות", imageUrl: `http://localhost:5000/Cabinets/c27.png` })
    await Products.create({ name: "ארונות", price: 1000, description: "ארונות מעוצבים יפייפה", category: "ארונות", imageUrl: `http://localhost:5000/Cabinets/c28.png` })
    await Products.create({ name: "ארונות", price: 1200, description: "ארונות מעוצבים יפייפה", category: "ארונות", imageUrl: `http://localhost:5000/Cabinets/c29.png` })
    await Products.create({ name: "ארונות", price: 1300, description: "ארונות מעוצבים יפייפה", category: "ארונות", imageUrl: `http://localhost:5000/Cabinets/c30.png` })
    await Products.create({ name: "ארונות", price: 1000, description: "ארונות מעוצבים יפייפה", category: "ארונות", imageUrl: `http://localhost:5000/Cabinets/c31.png` })
    await Products.create({ name: "ארונות", price: 800, description: "ארונות מעוצבים יפייפה", category: "ארונות", imageUrl: `http://localhost:5000/Cabinets/c32.png` })
    await Products.create({ name: "ארונות", price: 900, description: "ארונות מעוצבים יפייפה", category: "ארונות", imageUrl: `http://localhost:5000/Cabinets/c33.png` })
    await Products.create({ name: "ארונות", price: 850, description: "ארונות מעוצבים יפייפה", category: "ארונות", imageUrl: `http://localhost:5000/Cabinets/c34.png` })
    await Products.create({ name: "ארונות", price: 400, description: "ארונות מעוצבים יפייפה", category: "ארונות", imageUrl: `http://localhost:5000/Cabinets/c35.png` })
    await Products.create({ name: "ארונות", price: 700, description: "ארונות מעוצבים יפייפה", category: "ארונות", imageUrl: `http://localhost:5000/Cabinets/c36.png` })
    //"כלים סניטרים"
    await Products.create({ name: "כלים סניטרים", price: 750, description: "כלים סניטרים יוקרתיים", category: 'כלים סניטריים', imageUrl: `http://localhost:5000/Tools/t1.png` })
    await Products.create({ name: "כלים סניטרים", price: 1200, description: "כלים סניטרים יוקרתיים", category: 'כלים סניטריים', imageUrl: `http://localhost:5000/Tools/t2.png` })
    await Products.create({ name: "כלים סניטרים", price: 4100, description: "כלים סניטרים יוקרתיים", category: 'כלים סניטריים', imageUrl: `http://localhost:5000/Tools/t3.png` })
    await Products.create({ name: "כלים סניטרים", price: 700, description: "כלים סניטרים יוקרתיים", category: 'כלים סניטריים', imageUrl: `http://localhost:5000/Tools/t4.png` })
    await Products.create({ name: "כלים סניטרים", price: 800, description: "כלים סניטרים יוקרתיים", category: 'כלים סניטריים', imageUrl: `http://localhost:5000/Tools/t5.png` })
    await Products.create({ name: "כלים סניטרים", price: 7500, description: "כלים סניטרים יוקרתיים", category: 'כלים סניטריים', imageUrl: `http://localhost:5000/Tools/t6.png` })
    await Products.create({ name: "כלים סניטרים", price: 730, description: "כלים סניטרים יוקרתיים", category: 'כלים סניטריים', imageUrl: `http://localhost:5000/Tools/t7.png` })
    await Products.create({ name: "כלים סניטרים", price: 7120, description: "כלים סניטרים יוקרתיים", category: 'כלים סניטריים', imageUrl: `http://localhost:5000/Tools/t8.png` })
    await Products.create({ name: "כלים סניטרים", price: 700, description: "כלים סניטרים יוקרתיים", category: 'כלים סניטריים', imageUrl: `http://localhost:5000/Tools/t9.png` })
    await Products.create({ name: "כלים סניטרים", price: 800, description: "כלים סניטרים יוקרתיים", category: 'כלים סניטריים', imageUrl: `http://localhost:5000/Tools/t10.png` })
    await Products.create({ name: "כלים סניטרים", price: 900, description: "כלים סניטרים יוקרתיים", category: 'כלים סניטריים', imageUrl: `http://localhost:5000/Tools/t11.png` })
    await Products.create({ name: "כלים סניטרים", price: 700, description: "כלים סניטרים יוקרתיים", category: 'כלים סניטריים', imageUrl: `http://localhost:5000/Tools/t12.png` })
    await Products.create({ name: "כלים סניטרים", price: 600, description: "כלים סניטרים יוקרתיים", category: 'כלים סניטריים', imageUrl: `http://localhost:5000/Tools/t13.png` })
    await Products.create({ name: "כלים סניטרים", price: 300, description: "כלים סניטרים יוקרתיים", category: 'כלים סניטריים', imageUrl: `http://localhost:5000/Tools/t14.png` })
    await Products.create({ name: "כלים סניטרים", price: 500, description: "כלים סניטרים יוקרתיים", category: 'כלים סניטריים', imageUrl: `http://localhost:5000/Tools/t15.png` })
    await Products.create({ name: "כלים סניטרים", price: 550, description: "כלים סניטרים יוקרתיים", category: 'כלים סניטריים', imageUrl: `http://localhost:5000/Tools/t16.png` })
    await Products.create({ name: "כלים סניטרים", price: 650, description: "כלים סניטרים יוקרתיים", category: 'כלים סניטריים', imageUrl: `http://localhost:5000/Tools/t17.png` })
    await Products.create({ name: "כלים סניטרים", price: 800, description: "כלים סניטרים יוקרתיים", category: 'כלים סניטריים', imageUrl: `http://localhost:5000/Tools/t18.png` })
    await Products.create({ name: "כלים סניטרים", price: 700, description: "כלים סניטרים יוקרתיים", category: 'כלים סניטריים', imageUrl: `http://localhost:5000/Tools/t19.png` })

}
module.exports = fillProduct